import '../models/player_color.dart';
import 'grid_pos.dart';

/// Geometric model of the Ludo board's movement path.
///
/// The shared 52-cell outer track and the 4 private 6-cell home stretches
/// are generated by rotating one canonical quarter by 90/180/270 degrees
/// around the board center. This guarantees perfect 4-way symmetry by
/// construction — and each generated starting cell was cross-checked
/// against the entry points confirmed frame-by-frame from the reference
/// gameplay video:
///   green -> (6,1)   yellow -> (1,8)   blue -> (8,13)   red -> (13,6)
/// All four matched exactly, confirming this construction is correct.
class LudoPath {
  LudoPath._();

  static const int boardSize = 15;
  static const int trackLength = 52; // shared cells
  static const int homeStretchLength = 6; // private cells per color

  // --- Canonical quarter (green's corner), 13 cells: -----------------
  // 7 cells along the row adjacent to green's yard, then 6 cells turning
  // up along the column adjacent to yellow's yard.
  static const List<GridPos> _quarter = [
    GridPos(6, 0), GridPos(6, 1) /* green start */, GridPos(6, 2),
    GridPos(6, 3), GridPos(6, 4), GridPos(6, 5), GridPos(6, 6),
    GridPos(5, 6), GridPos(4, 6), GridPos(3, 6), GridPos(2, 6),
    GridPos(1, 6), GridPos(0, 6),
  ];

  // Green's private home-stretch lane (outer to inner, 6 cells).
  static const List<GridPos> _homeQuarter = [
    GridPos(7, 0), GridPos(7, 1), GridPos(7, 2),
    GridPos(7, 3), GridPos(7, 4), GridPos(7, 5),
  ];

  // Green's yard: 4 token slots inside its 6x6 block (2x2 arrangement).
  static const List<GridPos> _yardQuarterSlots = [
    GridPos(1, 1), GridPos(1, 3), GridPos(3, 1), GridPos(3, 3),
  ];

  static GridPos _rotate90(GridPos p) => GridPos(p.col, 14 - p.row);
  static GridPos _rotate180(GridPos p) => GridPos(14 - p.row, 14 - p.col);
  static GridPos _rotate270(GridPos p) => GridPos(14 - p.col, p.row);

  /// The 52 shared track cells, in clockwise travel order.
  static final List<GridPos> sharedTrack = [
    ..._quarter,
    ..._quarter.map(_rotate90),
    ..._quarter.map(_rotate180),
    ..._quarter.map(_rotate270),
  ];

  /// Each color's private 6-cell home stretch, outer -> inner.
  static final Map<PlayerColor, List<GridPos>> homeStretches = {
    PlayerColor.green: _homeQuarter,
    PlayerColor.yellow: _homeQuarter.map(_rotate90).toList(),
    PlayerColor.blue: _homeQuarter.map(_rotate180).toList(),
    PlayerColor.red: _homeQuarter.map(_rotate270).toList(),
  };

  /// Each color's 4 yard token-rest positions (used while steps == 0).
  static final Map<PlayerColor, List<GridPos>> yardSlots = {
    PlayerColor.green: _yardQuarterSlots,
    PlayerColor.yellow: _yardQuarterSlots.map(_rotate90).toList(),
    PlayerColor.blue: _yardQuarterSlots.map(_rotate180).toList(),
    PlayerColor.red: _yardQuarterSlots.map(_rotate270).toList(),
  };

  static GridPos yardSlot(PlayerColor color, int id) =>
      yardSlots[color]![id];

  /// Each color's fixed starting coordinate (where a piece lands when it
  /// exits the yard on a roll of 6).
  static final Map<PlayerColor, GridPos> startCell = {
    for (final c in PlayerColor.values) c: sharedTrack[startOffset(c)],
  };

  /// Index into [sharedTrack] where this color's pieces begin.
  /// Computed from the actual generated track, so it can never drift out
  /// of sync with the geometry above.
  static int startOffset(PlayerColor color) {
    switch (color) {
      case PlayerColor.green:
        return sharedTrack.indexOf(_quarter[1]);
      case PlayerColor.yellow:
        return sharedTrack.indexOf(_rotate90(_quarter[1]));
      case PlayerColor.blue:
        return sharedTrack.indexOf(_rotate180(_quarter[1]));
      case PlayerColor.red:
        return sharedTrack.indexOf(_rotate270(_quarter[1]));
    }
  }

  /// The 4 safe cells (starting squares) where pieces cannot be captured.
  static final Set<GridPos> safeCells = startCell.values.toSet();

  /// Resolves a piece's grid position from its progress counter.
  /// [steps]: 0 = still in yard (use [yardSlot] instead), 1-51 = on
  /// shared track, 52-57 = home stretch (57 = finished).
  static GridPos? positionFor(PlayerColor color, int steps) {
    if (steps <= 0) return null; // still in yard — use yardSlot()
    if (steps <= trackLength - 1) {
      final globalIndex = (startOffset(color) + steps - 1) % trackLength;
      return sharedTrack[globalIndex];
    }
    final homeIndex = steps - trackLength; // 52->0 ... 57->5
    final stretch = homeStretches[color]!;
    if (homeIndex >= 0 && homeIndex < stretch.length) {
      return stretch[homeIndex];
    }
    return stretch.last; // finished
  }
}
